In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr =np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = ([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
    np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros ((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.random.rand(5)

array([0.9925305 , 0.69545367, 0.70096559, 0.50359252, 0.65529206])

In [21]:
np.random.rand(5,5)

array([[0.65148523, 0.24012588, 0.53341645, 0.86962165, 0.18509163],
       [0.8742431 , 0.91899331, 0.1517188 , 0.50617013, 0.223692  ],
       [0.46538533, 0.77731897, 0.28449162, 0.48632924, 0.002879  ],
       [0.80910441, 0.28033514, 0.37810326, 0.34321447, 0.46941075],
       [0.99738937, 0.83732712, 0.50742803, 0.00319105, 0.53717062]])

In [22]:
np.random.randn(2)

array([-1.01653056,  1.47531734])

In [23]:
np.random.randn(4,4)

array([[ 0.12987214,  2.70364505,  1.59348978, -1.51218996],
       [ 0.4357293 , -0.99027238,  2.21696746,  1.27284537],
       [ 0.50417917,  0.37875697,  0.74196485, -0.65914192],
       [ 1.33225512, -0.70628346,  0.19689671, -2.57806912]])

In [24]:
np.random.randint(1,100)

93

In [25]:
np.random.randint(1,100, 10) 

array([58, 45, 61, 14, 72, 89,  6, 44, 68, 71])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranr = np.random.randint(0,50,10)

In [29]:
ranr

array([ 2,  6, 26, 10, 14, 48, 14, 23,  3,  8])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranr.max()

48

In [32]:
ranr.min()

2

In [33]:
ranr.argmax()

5

In [34]:
ranr.argmin()

0

In [35]:
arr.shape

(25,)

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.dtype

dtype('int32')

In [41]:
arr = np.arange (0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[2]

2

In [43]:
arr[:2]

array([0, 1])

In [44]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[-1:]

array([10])

In [46]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
arr[:8:2]

array([0, 2, 4, 6])

In [48]:
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr[:]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr[:] = 88

In [52]:
arr

array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88])

In [65]:
arr_2d = np.random.randint(0, 45, size = (3,3))
arr_2d

array([[ 6, 42, 35],
       [27, 43, 40],
       [20, 10,  5]])

In [66]:
arr_2d[1][1]

43

In [67]:
arr_2d[2,1]

10

In [68]:
arr_2d[:2,1:]

array([[42, 35],
       [43, 40]])

In [69]:
arr = np.arange(1,11)

In [70]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
bool_arr = arr > 5

In [73]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [74]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [75]:
arr[arr<3]

array([1, 2])

In [76]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [78]:
arr =  np.arange(0,11)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [82]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [83]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [84]:
arr * 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
1/0

ZeroDivisionError: division by zero

In [86]:
1 /arr

<ipython-input-86-148a20bab727>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 /arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [87]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [88]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [89]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [90]:
np.max(arr)

10

In [91]:
np.min(arr)

0

In [92]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])